root = "."
tmp_dir = "tmp"

[build]
cmd = "chmod +x ./scripts/build-ldflags.sh && bash ./scripts/build-ldflags.sh"
bin = "tmp/main"
full_bin = "./tmp/main"

include_ext = ["go", "html", "tmpl"]
exclude_dir = ["tmp", "vendor", "web/static/dist"]

[log]
time = true