apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zero-downtime
  annotations:
  # Uncomment for NGINX extra settings if needed
   nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - host: zerodt.danielokoronkwo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zero-downtime
                port:
                  number: 80
