apiVersion: v1
kind: Service
metadata:
  name: zero-downtime
  labels:
    app: zero-downtime
spec:
  selector:
    app: zero-downtime
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
